### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Poussinou** [ukanth/micopacks#1]
Hi,

What's the license of this project?

If it's something open-source like the GNU GPL license, we could add it to F-Droid if you're ok!

**Comment by ukanth** [comment]
Added License. It's apache 2.0. I have not added in F-droid because of some closed source components like Google license.

**Comment by Poussinou** [comment]
What are the closed source components? If it's just some assets, we can still add it with a flag. The source code of the app is floss and I don't see anything problematic in the Gradle, but maybe I miss something here.

**Comment by ukanth** [comment]
It has google license check. But if you disable it build.gradle, it should be fine.
